version: "3.9"

services:
  message_queue:
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file: .env
    profiles: ["message_queue"]

  database:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    profiles: ["database"]

  scraper:
    build:
      context: .
      dockerfile: scrapers/Dockerfile
    env_file: .env
    # The new, working command for the scraper service
    command: ["bash", "-c", "Xvfb :99 -screen 0 1024x768x24 & export DISPLAY=:99 && poetry run python scrapers/src/scraper.py"]
    profiles: ["scraper"]

  crawler:
    build:
      context: .
      dockerfile: scrapers/Dockerfile
    env_file: .env
    # The new, working command for the crawler service
    command: ["bash", "-c", "Xvfb :99 -screen 0 1024x768x24 & export DISPLAY=:99 && poetry run python scrapers/src/crawler.py"]
    profiles: ["crawler"]

  writer:
    build:
      context: .
      dockerfile: scrapers/Dockerfile
    env_file: .env
    command: ["python", "scrapers/src/writer.py"]
    profiles: ["writer"]

volumes:
  postgres_data:
