# Generated by Django 4.2.7 on 2023-12-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adres", models.CharField(max_length=200)),
                ("postcode", models.CharField(max_length=6)),
                ("stad", models.CharField(max_length=100)),
                ("buurt", models.CharField(max_length=100)),
                ("datescraped", models.DateTimeField(verbose_name="Date scraped")),
            ],
        ),
    ]
