# Generated by Django 4.2.7 on 2023-12-03 06:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("woonitor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="id",
        ),
        migrations.AddField(
            model_name="listing",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
