# Generated by Django 4.2.7 on 2023-12-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("woonitor", "0002_remove_listing_id_listing_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="uuid",
            field=models.UUIDField(
                default=123, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
