# Generated by Django 4.2.7 on 2023-12-03 07:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("woonitor", "0004_remove_listing_uuid_listing_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="oppervlakte",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="listing",
            name="vraagprijs",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="listing",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
