# Generated by Django 4.2.7 on 2023-12-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("woonitor", "0007_remove_listing_uuid_listing_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="url",
            field=models.CharField(
                default="https://www.funda.nl/koop/tilburg/appartement-42325627-enschotsestraat-375/",
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
