# Generated by Django 4.2.7 on 2023-12-03 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("woonitor", "0008_listing_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="postcode",
            field=models.CharField(
                max_length=6,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_format",
                        message="Enter a valid format (e.g., 2424DD)",
                        regex="^\\d{4}[A-Z]{2}",
                    )
                ],
            ),
        ),
    ]
