# Generated by Django 4.2.7 on 2023-12-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("woonitor", "0009_alter_listing_postcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="gemeente",
            field=models.CharField(default="GemeenteTilburg", max_length=100),
            preserve_default=False,
        ),
    ]
