# Generated by Django 4.2.7 on 2023-12-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("woonitor", "0010_listing_gemeente"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="verkocht",
            field=models.BooleanField(default=False),
        ),
    ]
