# Generated by Django 4.2.7 on 2023-12-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("woonitor", "0011_listing_verkocht"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="aangebodensinds",
            field=models.DateTimeField(default=None, verbose_name="Offered since"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="bouwjaar",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="listing",
            name="energielabel",
            field=models.CharField(default=None, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="verkoopdatum",
            field=models.DateTimeField(default=None, verbose_name="Sold on"),
            preserve_default=False,
        ),
    ]
