# Generated by Django 4.2.7 on 2023-12-03 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("woonitor", "0012_listing_aangebodensinds_listing_bouwjaar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="verkocht",
        ),
    ]
