# Generated by Django 4.2.7 on 2023-12-03 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("woonitor", "0013_remove_listing_verkocht"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="bouwjaar",
        ),
    ]
