# Generated by Django 4.2.7 on 2023-12-03 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("woonitor", "0014_remove_listing_bouwjaar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="gemeente",
        ),
    ]
