# Generated by Django 4.2.7 on 2023-12-03 19:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("woonitor", "0015_remove_listing_gemeente"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="oppervlakte",
        ),
    ]
