# Generated by Django 4.2.7 on 2023-12-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("woonitor", "0017_remove_listing_energielabel"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="verkooptijd",
            field=models.IntegerField(default=0),
        ),
    ]
