# Generated by Django 4.2.7 on 2023-12-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("woonitor", "0018_listing_verkooptijd"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="fundaID",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
