# Generated by Django 4.2.7 on 2023-12-12 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("woonitor", "0019_listing_fundaid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="fundaID",
        ),
    ]
