services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env
    profiles: ["redis"]

  crawler:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: ["python", "src/crawler.py"]
    profiles: ["crawler"]

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: ["python", "src/scraper.py"]
    profiles: ["scraper"]
