services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env

  crawler:
    build: ./crawler
    env_file: .env
    profiles: ["crawler"]

  worker:
    build: ./worker
    env_file: .env
    profiles: ["worker"]

