version: "3.9"

services:
  message_queue:
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file: .env
    profiles: ["message_queue"]
    networks:
      - woonitor-net

  database:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    profiles: ["database"]
    networks:
      - woonitor-net

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: ["xvfb-run", "python", "src/scraper.py"]
    profiles: ["scraper"]
    networks:
      - woonitor-net

  crawler:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: ["xvfb-run", "python", "src/crawler.py"]
    profiles: ["crawler"]
    networks:
      - woonitor-net
  
  writer:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: ["python", "src/writer.py"]
    profiles: ["writer"]
    networks:
      - woonitor-net

volumes:
  postgres_data:

networks:
  woonitor-net:
    external: true

