services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env
    profiles: ["redis"]

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CACHE_BUSTER: ${CACHE_BUSTER:-1}
    env_file: .env
    command: ["xvb-run", "python", "src/scraper.py"]
    profiles: ["scraper"]

  crawler:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CACHE_BUSTER: ${CACHE_BUSTER:-1}
    env_file: .env
    command: ["xvb-run", "python", "src/crawler.py"]
    profiles: ["crawler"]
